name: ${project.artifactId}
main: com.mcmiddleearth.autoteleport.AutoTeleportPlugin
version: ${project.version}
author: Eriol_Eandur
description: automated teleportation plugin
load: POSTWORLD
softdepend: [bukkit, guava, MCME-Connect, worldedit-core, worldedit-bukkit]
depend: [PluginUtils]
api-version: 1.15

commands:
    atp:
        description: manage auto teleport areas
        usage: invalid subcommand
permissions:
    autoteleport.*:
        description: Gives access to all auto teleport commands
        default: op
        children:
            autoteleport.user: true
    autoteleport.user:
        description: gives access to /atp command
        default: op
